# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfcc18ecd844c7ef3e8d7c45f7eab1de"
name = "function-app"
handle = "function-app-8"
application_url = "https://patio-next-meal-presidential.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ecomwork1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://patio-next-meal-presidential.trycloudflare.com/auth/callback",
  "https://patio-next-meal-presidential.trycloudflare.com/auth/shopify/callback",
  "https://patio-next-meal-presidential.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
